### ISSUE TITLE
CUDA OOM error in stage 9a.6

### ISSUE THREAD

**Issue by carlosfranzreb** [Voice-Privacy-Challenge/Voice-Privacy-Challenge-2022#25]
Hello,

I am trying to run the baseline with `tts_type=am_nsf_pytorch`. As shown below, I become a CUDA OOM error in stage 9a.6. My machine has a 4 GB GPU. Is it possible to reduce the memory requirements of this stage? Maybe emptying the cache between the steps of the stage, or reducing the batch size?

```log
Start inference (generation): ## stage 9a.6
Generating 1, 262,6345-64257-0003,0,140160,0, time cost: 0.854s
Generating 2, 147,3536-23268-0007,0,147040,0, time cost: 0.854s
...
Generating 279, 146,3536-23268-0002,0,167680,0, time cost: 0.931s
Generating 280, 304,8297-275154-0002,0,155840,0, time cost: 0.931s
Traceback (most recent call last):
  File "VPC22/nii_pytorch/projects/nsf/main.py", line 211, in <module>
    main()
  File "VPC22/nii_pytorch/projects/nsf/main.py", line 205, in main
    nii_nn_wrapper.f_inference_wrapper(args, model, device, \
  File "VPC22/nii_pytorch/core_scripts/nn_manager/nn_manager.py", line 603, in f_inference_wrapper
    data_gen = infer_func(data_in)
  File "VPC22/nii_pytorch/projects/nsf/model.py", line 903, in forward
    output = self.m_filter(har_source, noi_source, cond_feat, cut_f)
  File "VPC22/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "VPC22/nii_pytorch/projects/nsf/model.py", line 762, in forward
    har_component = l_har_block(har_component, cond_feat)
  File "VPC22/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "VPC22/nii_pytorch/projects/nsf/model.py", line 405, in forward
    tmp_hidden = tmp_hidden + l_conv(tmp_hidden) + context
  File "VPC22/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "VPC22/nii_pytorch/projects/nsf/model.py", line 97, in forward
    output = self.l_ac(super(Conv1dKeepLength, self).forward(x))
  File "VPC22/venv/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 263, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "VPC22/venv/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 259, in _conv_forward
    return F.conv1d(input, weight, bias, self.stride,
RuntimeError: CUDA out of memory. Tried to allocate 458.00 MiB (GPU 0; 3.82 GiB total capacity; 2.33 GiB already allocated; 123.38 MiB free; 2.41 GiB reserved in total by PyTorch)
```

Kind regards,
Carlos

**Comment by carlosfranzreb** [comment]
This issue is already addressed in the file `baseline/config.sh`:

```
	inference_batch_size_am=10           # use batch mode to accelrate generation speed for acoustic model
	                                     #  However, the larger the batch size is, the more GPU memory is required.
	                                     #  If Pytorch raises error on insufficient GPU memory in step a.5,
	                                     #  please reduce inference_batch_size_am
	inference_batch_size_wav=2           # use batch mode to accelrate generation speed for waveform model
	                                     #  Note that waveform model requires more GPU memory
	                                     #  If Pytorch raises error on insufficient GPU memory in step a.6,
	                                     #  please reduce inference_batch_size_wav
```

**Comment by carlosfranzreb** [comment]
This issue is already addressed in the file `baseline/config.sh`:

```
	inference_batch_size_am=10           # use batch mode to accelrate generation speed for acoustic model
	                                     #  However, the larger the batch size is, the more GPU memory is required.
	                                     #  If Pytorch raises error on insufficient GPU memory in step a.5,
	                                     #  please reduce inference_batch_size_am
	inference_batch_size_wav=2           # use batch mode to accelrate generation speed for waveform model
	                                     #  Note that waveform model requires more GPU memory
	                                     #  If Pytorch raises error on insufficient GPU memory in step a.6,
	                                     #  please reduce inference_batch_size_wav
```

**Comment by carlosfranzreb** [comment]
This issue is already addressed in the file `baseline/config.sh`:

```
	inference_batch_size_am=10           # use batch mode to accelrate generation speed for acoustic model
	                                     #  However, the larger the batch size is, the more GPU memory is required.
	                                     #  If Pytorch raises error on insufficient GPU memory in step a.5,
	                                     #  please reduce inference_batch_size_am
	inference_batch_size_wav=2           # use batch mode to accelrate generation speed for waveform model
	                                     #  Note that waveform model requires more GPU memory
	                                     #  If Pytorch raises error on insufficient GPU memory in step a.6,
	                                     #  please reduce inference_batch_size_wav
```
